export const BASE_URL = 'https://alsayafelectromechanical.com/lindsayandre/api/';

export const endpoints = {
  Login: 'user/login',
  Register: 'user/register',
  Logout: 'user/logout',
  SocialLogin: 'social-login',
  ResetPassword: 'reset-password',
  ForgotPassword: 'user/forgotpassword',
  VerifyCode: 'verify-code',
  CreatePost: '/user/posts',
  NewsFeed: '/user/news-feed',
  Like: '/user/react-post',
  Comment: '/user/post/comments',
  GetPost: '/user/posts/',
  ReportPost: '/user/report-post',
  Experiences: '/experiences',
  SharePost: '/user/share-post',
  MyPost: '/user/my-posts',
  UpdateProfile: 'user/profile/update',
  ContactUs: '/contact-us',
  Vote: '/user/poll-vote',
  GetContent: '/business-settings',
  OthersProfile: '/user/other-profile/',
  NotificationSetting: '/user/update-notification-status',
  Notifications: 'user/notifications',
  PrivacySetting: '/user/update-account-status',
  Ads: '/ads',
  UpdateAdPrivacy: '/update-privacy-status',
  CalculateAdRates: '/calculate-ads-rate?days=',
  Cards: '/user/cards/list',
  AddCard: '/user/cards/add',
  MakeDefaultCard: 'user/cards/default',
};
