export const BASE_URL = 'https://alsayafelectromechanical.com/lindsayandre/api/';

export const endpoints = {
  Login: 'user/login',
  Register: 'user/register',
  Logout: 'user/logout',
  SocialLogin: 'social-login',
  ResetPassword: 'user/resetpassword',
  ForgotPassword: 'user/forgotpassword',
  VerifyCode: 'verify-code',
  Category: (id: string) => 'category/list?parent_id=' + id,
  FilterCategoryByTitle: (title: string) => 'category/list?filter_by_title=' + title,
  AllCategory: 'category/list?parent_id=eyJpdiI6ImNDT0g3M0Rxd25zdGJcL0lPU1hiUHNnPT0iLCJ2YWx1ZSI6IkcydkpXZlwvam1Ed3NDSGdEeGV5OHJ3PT0iLCJtYWMiOiJjY2FjYTI0M2MwN2UyZjA3NjJjNmM4NmZjNzExN2RhYjhkYjc0ODUwNGE0NTQ1M2UyNmU4MTRlZTg0NTA3ZjNiIn0=',
  NewsFeed: '/user/news-feed',
  Like: '/user/react-post',
  Comment: '/user/post/comments',
  GetPost: '/user/posts/',
  ReportPost: '/user/report-post',
  Experiences: '/experiences',
  SharePost: '/user/share-post',
  MyPost: '/user/my-posts',
  UpdateProfile: 'user/profile/update',
  ContactUs: '/contact-us',
  Vote: '/user/poll-vote',
  GetContent: '/business-settings',
  OthersProfile: '/user/other-profile/',
  NotificationSetting: '/user/update-notification-status',
  Notifications: 'user/notifications',
  PrivacySetting: '/user/update-account-status',
  Ads: '/ads',
  UpdateAdPrivacy: '/update-privacy-status',
  CalculateAdRates: '/calculate-ads-rate?days=',
  Cards: '/user/cards/list',
  AddCard: '/user/cards/add',
  MakeDefaultCard: 'user/cards/default',
};
